print("=================================")
print("AUTO-UPDATER TEST SUCCESSFUL!")
print("=================================")
print("Loaded from GitHub at: " .. os.date("%X"))
print("Version: 1")
print("If you see this, the loader works!")
print("=================================")